name: Delete Feature Branch

on:
  repository_dispatch:
    types:
      - delete-feature-branch

permissions:
  contents: read

jobs:
  delete:
    runs-on: ubuntu-latest

    steps:
      - name: Generate Internal GitHub App token
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.SYNC_APP_ID }}
          private-key: ${{ secrets.SYNC_APP_PRIVATE_KEY }}
          owner: GitHubActionsPOC
          repositories: gh-blue-yonder-testing-prod-15-02

      - name: Delete Branch
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
          BRANCH: ${{ github.event.client_payload.branch }}
        run: |
          echo "Deleting $BRANCH"

          if gh api repos/${{ github.repository }}/branches/$BRANCH >/dev/null 2>&1; then
            gh api \
              --method DELETE \
              repos/${{ github.repository }}/git/refs/heads/$BRANCH
          else
            echo "Branch does not exist"
          fi
