name: Vendor Sync
on:
  repository_dispatch:
    types:
      - BY-branch-updated
  workflow_dispatch:
  
jobs:
  sync-vendor:
    runs-on: ubuntu-latest

    env:
      BRANCH_NAME: ${{ github.event.client_payload.branch || 'main' }}

    permissions:
      contents: write
      pull-requests: write

    steps:

      - name: Checkout internal repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Generate Internal GitHub App token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.SYNC_APP_ID }}
          private-key: ${{ secrets.SYNC_APP_PRIVATE_KEY }}
          owner: GitHubActionsPOC
          repositories: gh-blue-yonder-testing-prod-15-02

      - name: Generate Vendor GitHub App token
        id: vendor_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.VENDOR_APP_ID }}
          private-key: ${{ secrets.VENDOR_APP_PRIVATE_KEY }}
          owner: guptadiya
          repositories: sync-test-prod-15-01
          
      - name: Configure vendor remote
        run: |
          git remote remove vendor || true
      
          git remote add vendor https://github.com/guptadiya/sync-test-prod-15-01.git
      
          
      
      - name: Configure Git identity
        run: |
          git config --global user.name "vendor-sync-bot"
          git config --global user.email "vendor-sync-bot@users.noreply.github.com"
          
      - name: Configure GitHub authentication
        env:
          TOKEN: ${{ steps.generate_token.outputs.token }}
        run: |
          git config --global --unset-all http.https://github.com/.extraheader || true
          
          git config --global http.https://github.com/GitHubActionsPOC/gh-blue-yonder-testing-prod-15-02.git.extraheader \
          "AUTHORIZATION: basic $(echo -n x-access-token:${TOKEN} | base64)"
          
      - name: Configure GitHub authentication
        env:
          TOKEN: ${{ steps.vendor_token.outputs.token }}
        run: |
          git config --global --unset-all http.https://github.com/.extraheader || true
      
          git config --global http.https://github.com/guptadiya/sync-test-prod-15-01.git.extraheader \
          "AUTHORIZATION: basic $(echo -n x-access-token:${TOKEN} | base64)"


      - name: Fetch vendor branch
        run: |
          git fetch vendor ${BRANCH_NAME}
          
      - name: Merge vendor branch into local branch
        run: |
          git checkout -B ${BRANCH_NAME}
          git merge vendor/${BRANCH_NAME} \
          --allow-unrelated-histories \
          -X theirs \
          -m "Auto sync vendor ${BRANCH_NAME}"
          
      - name: Remove internal workflow file
        run: |
          rm -f .github/workflows/notify-pep.yml
          git add .github/workflows/notify-pep.yml || true
          git commit -m "Remove internal workflow before sync push" || true
          
      - name: Configure origin remote
        env:
          TOKEN: ${{ steps.generate_token.outputs.token }}
        run: |
          git remote set-url origin \
          https://x-access-token:${TOKEN}@github.com/GitHubActionsPOC/gh-blue-yonder-testing-prod-15-02.git
          
      - name: Push directly to target branch
        run: |
          git push origin ${BRANCH_NAME} --force
