name: Sync develop branch to Vendor Repo

on:
  workflow_dispatch:

  push:
    branches:
      - develop
jobs:
  sync-to-vendor:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:

      - name: Checkout source repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate GitHub App token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.VENDOR_APP_ID }}
          private-key: ${{ secrets.VENDOR_APP_PRIVATE_KEY }}
          owner: guptadiya
          repositories: sync-test-prod-15-01

      - name: Configure Git identity
        run: |
          git config --global user.name "repo-sync-bot"
          git config --global user.email "repo-sync-bot@users.noreply.github.com"
          
      - name: Configure vendor remote
        env:
          TOKEN: ${{ steps.generate_token.outputs.token }}
        run: |
          git remote remove vendor || true

          git remote add vendor "https://x-access-token:${TOKEN}@github.com/guptadiya/sync-test-prod-15-01.git"

      - name: Configure GitHub authentication
        env:
          TOKEN: ${{ steps.generate_token.outputs.token }}
        run: |
          git config --global --unset-all http.https://github.com/.extraheader || true
      
          git config --global http.https://github.com/guptadiya/sync-test-prod-15-01.git.extraheader \
          "AUTHORIZATION: basic $(echo -n x-access-token:${TOKEN} | base64)"
    
      - name: Fetch vendor develop
        run: |
          git fetch vendor develop

      - name: Merge source develop into vendor develop locally
        run: |
          git checkout -B develop vendor/develop

          git remote rename origin source

          git fetch source

          git merge source/develop \
            --allow-unrelated-histories \
            -X theirs \
            -m "Sync source develop branch"

      - name: Remove internal workflow file
        run: |
          rm -f .github/workflows/sync-repo.yml

          git add .github/workflows/sync-repo.yml || true

          git commit -m "Remove internal workflow before vendor sync" || true

      - name: Push directly to vendor develop
        run: |
          git push vendor develop
