name: BYReady Trigger

on:
  push:
    tags:
      - '**-BYReady'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Echo Information
        run: |
          echo "BYReady tag detected!"
          echo "Tag Name: ${{ github.ref_name }}"
